name: Python application

on: [push]

jobs:
  build:
    

    runs-on: ubuntu-latest

    steps:
    - name: Authenticate with Google Cloud
      uses: actions/gcloud/auth@master
      with:
        secrets: ${{secrets.GCP_SA_FDK_JENKINS_GCR}}






