name: Python application

on: [push]

jobs:
  build:
    

    runs-on: ubuntu-latest

    steps:
    - name: Authenticate with Google Cloud
      uses: actions/gcloud/auth@master
      with:
        secrets: ${{secrets.GCP_SA_ACTIONS}}
    - name: Authorise Docker on GCP
      uses: actions/gcloud/cli@master
      with:
        args: auth configure docker -q






