name: Python application

on: [push]

jobs:
  build:
    

    runs-on: ubuntu-latest

    steps:
    - name: Connect to Google Cloud
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: fdk-dev
        APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_FDK_JENKINS_GCR }}
      with:
        args: info






